const fs = require('fs');

const iniciarContent = [
  '@echo off',
  'title JB Cunha - Central de Operacoes',
  'chcp 65001 >nul',
  'cd /d "%~dp0"',
  '',
  'echo ================================================================',
  'echo         JB CUNHA - CENTRAL DE OPERACOES E OFICINA',
  'echo ================================================================',
  'echo.',
  'echo  [1/2] Verificando se o servidor ja esta ativo...',
  '',
  ':: Verifica se a porta 3000 ja esta em uso',
  'powershell -NoProfile -ExecutionPolicy Bypass -Command "if (Get-NetTCPConnection -LocalPort 3000 -State Listen -ErrorAction SilentlyContinue) { exit 1 } else { exit 0 }"',
  'if %ERRORLEVEL% EQU 1 (',
  '    echo  [AVISO] O servidor ja esta rodando na porta 3000!',
  '    echo  Abrindo o navegador...',
  '    start "" "http://localhost:3000"',
  '    echo.',
  '    echo  Pressione qualquer tecla para fechar esta janela.',
  '    pause >nul',
  '    exit /b 0',
  ')',
  '',
  ':: Garante que o diretorio do Node.js esteja no PATH da sessao atual',
  'if exist "%ProgramFiles%\\nodejs" set "PATH=%ProgramFiles%\\nodejs;%PATH%"',
  'if exist "%ProgramFiles(x86)%\\nodejs" set "PATH=%ProgramFiles(x86)%\\nodejs;%PATH%"',
  'if exist "%LocalAppData%\\Programs\\nodejs" set "PATH=%LocalAppData%\\Programs\\nodejs;%PATH%"',
  '',
  ':: Verifica se o Node.js esta instalado',
  'where node >nul 2>nul',
  'if %ERRORLEVEL% NEQ 0 (',
  '    echo.',
  '    echo  [ERRO] O Node.js nao foi encontrado no sistema!',
  '    echo  Por favor, instale o Node.js em https://nodejs.org/ e tente novamente.',
  '    echo.',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'echo  [2/2] Iniciando o servidor Node.js...',
  'echo.',
  'echo  - Painel da Oficina: http://localhost:3000',
  'echo  - Modo TV:          http://localhost:3000/#tv',
  'echo.',
  'echo  Mantenha esta janela aberta enquanto estiver utilizando o sistema.',
  'echo  Para desligar, feche esta janela ou use o arquivo PARAR_OFICINA.bat',
  'echo ================================================================',
  'echo.',
  '',
  ':: Abre o navegador automaticamente quando o servidor estiver pronto na porta 3000',
  'start "" powershell -WindowStyle Hidden -NoProfile -ExecutionPolicy Bypass -Command "$n=0; while($n -lt 30){ try { $c=New-Object System.Net.Sockets.TcpClient(\'127.0.0.1\',3000); $c.Close(); Start-Process \'http://localhost:3000\'; break } catch { Start-Sleep -Milliseconds 400; $n++ } }"',
  '',
  ':: Inicia o servidor Node.js',
  'node api-gateway/server.js',
  '',
  'echo.',
  'echo O servidor foi encerrado.',
  'pause',
  ''
].join('\r\n');

const pararContent = [
  '@echo off',
  'title JB Cunha - Desligar Sistema',
  'chcp 65001 >nul',
  'cd /d "%~dp0"',
  '',
  'echo ================================================================',
  'echo         JB CUNHA - DESLIGAR CENTRAL DE OPERACOES',
  'echo ================================================================',
  'echo.',
  'echo  Encerrando os processos do servidor na porta 3000...',
  'echo.',
  '',
  'powershell -NoProfile -ExecutionPolicy Bypass -Command "$conns = Get-NetTCPConnection -LocalPort 3000 -State Listen -ErrorAction SilentlyContinue; if ($conns) { $conns | Select-Object -ExpandProperty OwningProcess -Unique | ForEach-Object { Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue }; Write-Host \'  [OK] Servidor desligado com sucesso!\' -ForegroundColor Green } else { Write-Host \'  [INFO] O servidor ja estava desligado.\' -ForegroundColor Yellow }"',
  '',
  'echo.',
  'echo ================================================================',
  'echo  Concluido! O ambiente foi desligado.',
  'echo ================================================================',
  'echo.',
  'timeout /t 3 >nul 2>&1',
  ''
].join('\r\n');

fs.writeFileSync('INICIAR_OFICINA.bat', iniciarContent, { encoding: 'utf8' });
fs.writeFileSync('PARAR_OFICINA.bat', pararContent, { encoding: 'utf8' });
console.log('Arquivos .bat regerados com CRLF e sintaxe corrigida com sucesso!');
